export const SAMPLE_EVENTS = [
  {
    title: "Personal Safety Workshop — Accra",
    slug: "personal-safety-accra-2026",
    description: "A half-day intensive personal safety workshop for women in Greater Accra. Covers situational awareness, safety circles, de-escalation, and emergency planning. Led by Zarinah Knows.",
    type: "workshop",
    date: "2026-08-15T09:00:00Z",
    endDate: "2026-08-15T13:00:00Z",
    location: "East Legon, Accra, Ghana",
    isVirtual: false,
    maxAttendees: 40,
    registeredCount: 12,
    isPublished: true,
    organizer: "SafeHer Foundation",
  },
  {
    title: "Online Safety for University Students — Webinar",
    slug: "online-safety-webinar-sept-2026",
    description: "Free webinar covering phone privacy, spy app detection, sextortion response, and social media safety. Open to all university students across Africa.",
    type: "webinar",
    date: "2026-09-10T14:00:00Z",
    endDate: "2026-09-10T15:30:00Z",
    location: "Online (Zoom)",
    isVirtual: true,
    meetingLink: "https://zoom.us/j/placeholder",
    maxAttendees: 200,
    registeredCount: 45,
    isPublished: true,
    organizer: "DK Cyber",
  },
  {
    title: "Mobile Money Fraud Protection — Kumasi Workshop",
    slug: "momo-fraud-kumasi-2026",
    description: "A practical workshop teaching women in Kumasi how to protect themselves from mobile money fraud, SIM swap attacks, and fake agent scams.",
    type: "workshop",
    date: "2026-10-05T10:00:00Z",
    endDate: "2026-10-05T14:00:00Z",
    location: "Kumasi, Ashanti Region, Ghana",
    isVirtual: false,
    maxAttendees: 30,
    registeredCount: 8,
    isPublished: true,
    organizer: "SafeHer Foundation",
  },
  {
    title: "SafeHer Academy Launch Event",
    slug: "academy-launch-2026",
    description: "The official launch of SafeHer Academy — our free online learning platform. Join us for the announcement, live demos, and the first cohort enrollment.",
    type: "conference",
    date: "2026-07-20T10:00:00Z",
    endDate: "2026-07-20T16:00:00Z",
    location: "Accra International Conference Centre",
    isVirtual: false,
    maxAttendees: 150,
    registeredCount: 67,
    isPublished: true,
    organizer: "SafeHer Foundation",
  },
  {
    title: "Campus Safety Training — University of Ghana",
    slug: "campus-safety-ug-2026",
    description: "A full-day safety training programme for female students at the University of Ghana, Legon. Covers hostel safety, social situations, and emergency protocols.",
    type: "training",
    date: "2026-11-12T08:00:00Z",
    endDate: "2026-11-12T16:00:00Z",
    location: "University of Ghana, Legon",
    isVirtual: false,
    maxAttendees: 60,
    registeredCount: 0,
    isPublished: true,
    organizer: "SafeHer Foundation",
  },
];
