export const SAMPLE_COURSES = [
  {
    title: "Pretty Girl, Save Yourself: Personal Safety Foundations",
    slug: "personal-safety-foundations",
    excerpt: "The foundational SafeHers curriculum. Learn situational awareness, instinct, secure movement, and personal protection protocols.",
    description: "Based on the book 30 Ways Pretty Girls Can Save Themselves, this course teaches the core safety principles every woman should know. From recognising danger signals to building personal security protocols, you will leave equipped with practical knowledge you can use immediately.",
    category: "personal-safety",
    level: "beginner",
    durationHours: 6,
    instructor: "Zarinah Knows",
    isFree: true,
    isPublished: true,
    tags: ["personal-safety", "awareness", "foundation", "self-defence"],
    learningOutcomes: [
      "Identify and respond to common threat patterns",
      "Build a personal safety protocol for daily routines",
      "Understand body language and environmental awareness",
      "Create and maintain a trusted safety circle",
      "Respond effectively to confrontational situations",
      "Develop a personal emergency plan",
    ],
    modules: [
      {
        title: "Understanding Your Safety Landscape", slug: "safety-landscape",
        description: "Learn to read your environment and recognise risk before it becomes danger.", order: 0,
        lessons: [
          { title: "Welcome to SafeHer Academy", slug: "welcome", type: "text", durationMinutes: 5, order: 0, quizQuestions: [],
            content: "Welcome to Pretty Girl, Save Yourself — the foundational course from SafeHer Foundation. This programme is built on decades of security expertise and designed for women across Africa. Over the next modules, you will learn practical, evidence-based safety skills you can use immediately.\n\nThis course is based on the book 30 Ways Pretty Girls Can Save Themselves by Zarinah Knows. It has been adapted for the African context in collaboration with DK Cyber.\n\nBy the end of this course, you will have a personal safety protocol, a trusted safety circle, and the confidence to protect yourself in everyday situations." },
          { title: "The 30 Ways Framework", slug: "30-ways-framework", type: "text", durationMinutes: 15, order: 1, quizQuestions: [],
            content: "The 30 Ways framework was developed by Zarinah Knows over nearly a decade of teaching teen girls and women. It covers four pillars:\n\n1. Personal Awareness — knowing your environment and trusting your instincts\n2. Home Safety — securing the place you sleep\n3. Digital Security — protecting your online presence and devices\n4. Financial Protection — safeguarding your money and independence\n\nEach pillar builds on the last. In this course, we focus on Personal Awareness and the daily protocols that keep you safe." },
          { title: "Situational Awareness: The Colour Code", slug: "situational-awareness", type: "text", durationMinutes: 20, order: 2,
            quizQuestions: [
              { question: "What does 'Condition Yellow' mean in the awareness colour code?", options: ["Completely relaxed and unaware", "Relaxed but alert, scanning your environment", "Specific threat identified", "Active danger, fight or flight"], correctIndex: 1, explanation: "Condition Yellow is the ideal everyday state — relaxed but deliberately aware of your surroundings." },
              { question: "What is the first step in situational awareness?", options: ["Running away from danger", "Observing your environment", "Calling the police", "Ignoring strangers"], correctIndex: 1, explanation: "Observation is the foundation — you must first notice before you can assess and respond." },
            ],
            content: "Situational awareness is the foundation of personal safety. It means paying deliberate attention to what is happening around you — who is near you, what is normal for the environment, and what feels out of place.\n\nThe Colour Code of Awareness:\n\n• White — Unaware, distracted (headphones in, phone out, not looking around). This is when you are most vulnerable.\n• Yellow — Relaxed but alert. You are aware of who is around you and what is normal. This should be your default state in public.\n• Orange — Something has caught your attention. A person, a vehicle, a situation that feels off. You have a specific concern.\n• Red — A threat is confirmed. You act: move, call for help, defend.\n\nPractical Task: For the next 3 days, practice staying in Condition Yellow whenever you leave your home. Notice who is around you, what vehicles are nearby, and where the exits are." },
        ],
      },
      {
        title: "Personal Security Protocols", slug: "personal-protocols",
        description: "Build daily habits and protocols that make you a harder target.", order: 1,
        lessons: [
          { title: "Building Your Safety Circle", slug: "safety-circle", type: "text", durationMinutes: 15, order: 0, quizQuestions: [
              { question: "How many people should be in your safety circle?", options: ["1", "2-4", "10+", "Everyone you know"], correctIndex: 1, explanation: "A safety circle of 2-4 trusted people is manageable and reliable." },
            ],
            content: "A safety circle is a small group of 2-4 trusted people who know your routines, can be reached in an emergency, and will act without hesitation.\n\nHow to build yours:\n1. Choose people who are reliable, available, and trustworthy — not just close friends\n2. Share your daily routine with them (work schedule, regular routes)\n3. Agree on check-in protocols (e.g. text when you arrive home)\n4. Establish a code word that means 'I need help immediately'\n5. Test it — send the code word and see how fast they respond\n\nPractical Task: Identify your 2-4 safety circle members. Have the conversation with each of them this week. Set up a group chat with a clear name." },
          { title: "Route Security and Daily Patterns", slug: "route-security", type: "text", durationMinutes: 15, order: 1, quizQuestions: [
              { question: "Why should you vary your daily route?", options: ["To explore new places", "To avoid traffic", "To disrupt predictable patterns", "To get exercise"], correctIndex: 2, explanation: "Varying routes makes it harder for anyone to anticipate your movements." },
            ],
            content: "Most threats exploit predictability. If you take the same route at the same time every day, an attacker can plan around your pattern.\n\nRoute Security Basics:\n• Have at least 3 different routes to your regular destinations\n• Vary your departure times by 10-15 minutes\n• Know the safe spots on each route (shops, petrol stations, police posts)\n• Share your location with your safety circle when travelling alone\n• Avoid shortcuts through isolated areas, especially after dark\n\nPractical Task: Map out 3 different routes from your home to your most frequent destination. Identify at least 2 safe spots on each route." },
          { title: "Responding to Being Followed", slug: "being-followed", type: "text", durationMinutes: 20, order: 2, quizQuestions: [],
            content: "If you suspect you are being followed:\n\n1. Do NOT go home — you will reveal where you live\n2. Change your pace — speed up or slow down and see if they match\n3. Cross the street — do they cross too?\n4. Make 4 right turns — if they are still behind you after a full square, you are being followed\n5. Head to a populated, well-lit area — a busy shop, a petrol station, a police post\n6. Call your safety circle — use your code word\n7. If approached, make noise — attract attention\n\nPractical Task: Walk through the 4-right-turn test mentally for your neighbourhood. Know where you would go." },
        ],
      },
      {
        title: "Emergency Preparedness", slug: "emergency-prep",
        description: "Plan for the worst so you can respond with clarity.", order: 2,
        lessons: [
          { title: "Your Emergency Contact Plan", slug: "emergency-contacts", type: "activity", durationMinutes: 20, order: 0, quizQuestions: [],
            content: "Every woman should have an emergency contact plan — a list of numbers you can reach without thinking, stored both in your phone and on paper.\n\nYour plan should include:\n• Local police emergency number\n• Nearest police station direct line\n• Hospital/clinic nearest to your home and workplace\n• Your safety circle (2-4 people)\n• A trusted family member\n• DOVVSU (Domestic Violence & Victim Support Unit) if in Ghana: 0800-111-222\n\nPractical Task: Fill out your Emergency Contact Plan in the SafeHer Academy Safety Plan. Store a physical copy in your bag." },
          { title: "De-escalation and Boundary Setting", slug: "de-escalation", type: "text", durationMinutes: 20, order: 1, quizQuestions: [
              { question: "What is the best first response when a stranger becomes aggressive?", options: ["Fight back immediately", "Create distance and use a firm voice", "Freeze and hope they leave", "Argue your point"], correctIndex: 1, explanation: "Creating physical distance while using a confident, firm voice is the safest first response." },
            ],
            content: "De-escalation is the art of reducing tension before a situation becomes physical. It is not weakness — it is strategy.\n\nKey principles:\n• Maintain distance — never let an aggressor get within arm's reach\n• Use a firm, calm voice — not aggressive, not pleading\n• Set clear boundaries: 'Stop. Do not come closer.'\n• Keep your hands visible and in front of you\n• Look for exits — always know where you can move\n• Do not turn your back on a threat\n\nIf de-escalation fails, your priority is escape, not confrontation." },
          { title: "Course Review and Safety Plan", slug: "course-review", type: "quiz", durationMinutes: 15, order: 2,
            quizQuestions: [
              { question: "What is Condition Yellow?", options: ["Completely unaware", "Relaxed but alert", "Specific threat identified", "Active danger"], correctIndex: 1, explanation: "Yellow is your default public awareness state." },
              { question: "What should you NOT do if you think you are being followed?", options: ["Cross the street", "Go directly home", "Head to a busy area", "Call your safety circle"], correctIndex: 1, explanation: "Never lead a follower to your home." },
              { question: "How many routes should you have to regular destinations?", options: ["1", "At least 3", "It doesn't matter", "As many as possible"], correctIndex: 1, explanation: "At least 3 routes prevents pattern predictability." },
            ],
            content: "Final review quiz. Complete this to earn your certificate." },
        ],
      },
    ],
  },
  {
    title: "Mobile Money Fraud and Financial Safety",
    slug: "mobile-money-fraud",
    excerpt: "Protect yourself from mobile money fraud, SIM swap attacks, and financial scams targeting women across Africa.",
    description: "Mobile money has transformed life across Africa — but it has also created new fraud vectors. This course covers MoMo fraud, SIM swap attacks, fake agent scams, and financial safety practices built for African digital economies.",
    category: "financial-safety",
    level: "beginner",
    durationHours: 4,
    instructor: "DK Cyber",
    isFree: true,
    isPublished: true,
    tags: ["mobile-money", "fraud", "financial-safety", "momo"],
    learningOutcomes: [
      "Identify common mobile money fraud techniques",
      "Protect your MoMo and bank accounts from SIM swap attacks",
      "Recognise fake agent and wrong-transfer scams",
      "Set up account security and transaction alerts",
      "Report fraud to the correct authorities",
    ],
    modules: [
      {
        title: "The Mobile Money Threat Landscape", slug: "momo-threats",
        description: "Understand how mobile money fraud works in Ghana, Nigeria, and across Africa.", order: 0,
        lessons: [
          { title: "How Mobile Money Fraud Works", slug: "how-fraud-works", type: "text", durationMinutes: 20, order: 0, quizQuestions: [],
            content: "Mobile money fraud in Africa follows predictable patterns. The most common techniques:\n\n1. Fake customer service calls — someone calls pretending to be MTN, Vodafone, or your bank and asks for your PIN\n2. Wrong transfer scams — a stranger sends money 'by mistake' and asks you to return it (the original transfer is reversed after you send your own money)\n3. SIM swap attacks — a fraudster convinces your mobile operator to transfer your number to a new SIM\n4. Social engineering via WhatsApp — fake prize notifications, loan offers, or romance scams\n5. Fake agent fraud — someone poses as a mobile money agent and asks you to dial a code\n\nRule #1: No legitimate operator will ever call you and ask for your PIN. Ever." },
          { title: "SIM Swap Attacks Explained", slug: "sim-swap", type: "text", durationMinutes: 15, order: 1,
            quizQuestions: [
              { question: "What is a SIM swap attack?", options: ["Physically stealing someone's phone", "Transferring a phone number to a new SIM card", "Hacking a phone's operating system", "Cloning a SIM card"], correctIndex: 1, explanation: "SIM swap attacks involve social engineering the mobile operator to transfer your number." },
            ],
            content: "A SIM swap attack is when a fraudster convinces your mobile operator to transfer your number to a new SIM card they control. Once they have your number, they can:\n• Access your mobile money accounts\n• Reset your passwords\n• Intercept your verification codes\n\nSigns your SIM has been swapped:\n• Your phone suddenly loses signal\n• You cannot make calls or send texts\n• You receive notifications about changes you did not make\n\nHow to protect yourself:\n• Set a SIM PIN with your operator\n• Never share your ID number with callers\n• Register for SIM swap alerts\n• Use app-based 2FA instead of SMS 2FA where possible" },
          { title: "Fake Agent and Reversal Scams", slug: "fake-agents", type: "text", durationMinutes: 15, order: 2, quizQuestions: [
              { question: "If a stranger sends you money 'by mistake' and asks you to send it back, what should you do?", options: ["Send it back immediately", "Keep the money", "Do nothing — tell them to contact their operator", "Block them"], correctIndex: 2, explanation: "Never send money back directly — the original transfer can be reversed, leaving you out of pocket." },
            ],
            content: "Fake agent scams and wrong-transfer scams are extremely common:\n\nFake Agent Scam:\nSomeone approaches you pretending to be a mobile money agent. They ask you to dial a code 'to receive your money.' The code actually transfers money FROM your account.\n\nWrong Transfer Scam:\nA stranger sends money to your account and then contacts you saying it was a mistake. They ask you to send it back. After you do, they reverse the original transaction — and now you have lost your own money.\n\nProtection:\n• Never dial codes given to you by strangers\n• If someone sends you money 'by mistake,' tell them to contact their operator\n• Only use verified mobile money agents with proper signage and ID" },
          { title: "Setting Up Financial Security", slug: "financial-security", type: "activity", durationMinutes: 20, order: 3,
            quizQuestions: [],
            content: "Practical security setup:\n\n1. Set a SIM PIN with your mobile operator today\n2. Enable transaction alerts (SMS or push notifications) for all MoMo accounts\n3. Set up app-based 2FA (Google Authenticator) on any account that supports it\n4. Never share your MoMo PIN with anyone — including family\n5. Use a different PIN for your phone lock, SIM, and MoMo\n6. Register your MoMo account with your real ID (makes recovery easier if compromised)\n\nPractical Task: Complete all 6 steps above today. Check each one off in your SafeHer Academy Safety Plan." },
          { title: "Reporting Fraud and Recovery", slug: "reporting-fraud", type: "text", durationMinutes: 15, order: 4,
            quizQuestions: [
              { question: "What is the FIRST thing you should do if you suspect your MoMo account has been compromised?", options: ["Post about it on social media", "Call the police", "Lock your MoMo account immediately", "Wait and see if money is taken"], correctIndex: 2, explanation: "Lock your account first to prevent further losses, then report." },
            ],
            content: "If you have been defrauded:\n\n1. Lock your MoMo account immediately — call your operator's fraud line\n2. Report to your mobile operator (MTN: 100, Vodafone: 100)\n3. File a police report at your local station\n4. Report to the Economic and Organised Crime Office (EOCO) if in Ghana\n5. Keep all evidence — screenshots, call logs, transaction IDs\n6. Do NOT engage further with the fraudster\n\nPractical Task: Save your operator's fraud hotline in your phone right now." },
        ],
      },
    ],
  },
  {
    title: "Phone Privacy and Spy App Detection",
    slug: "phone-privacy-spy-detection",
    excerpt: "Learn to detect spyware, secure your phone, and protect your digital privacy from intimate partner surveillance.",
    description: "Your phone knows everything about you. This course teaches you how to check for spy apps, lock down your device, manage app permissions, and protect yourself from digital surveillance — whether from a partner, a stranger, or a scammer.",
    category: "online-safety",
    level: "beginner",
    durationHours: 3,
    instructor: "DK Cyber",
    isFree: true,
    isPublished: true,
    tags: ["phone-privacy", "spyware", "digital-safety", "surveillance"],
    learningOutcomes: [
      "Check your phone for spy apps and stalkerware",
      "Configure privacy settings on Android and iPhone",
      "Manage app permissions to protect personal data",
      "Detect signs of digital surveillance",
      "Secure your accounts with strong passwords and 2FA",
    ],
    modules: [
      {
        title: "Is Your Phone Compromised?", slug: "phone-compromised",
        description: "Learn the warning signs and how to check your device.", order: 0,
        lessons: [
          { title: "Signs Your Phone May Have Spyware", slug: "spyware-signs", type: "text", durationMinutes: 15, order: 0, quizQuestions: [],
            content: "Spyware and stalkerware are apps that secretly monitor your calls, messages, location, and photos. They are often installed by intimate partners, but can also come from malicious links.\n\nWarning signs:\n• Battery drains faster than usual\n• Phone is hot even when not in use\n• Unusual data usage spikes\n• Phone takes longer to shut down\n• You see apps you do not recognise\n• Someone knows things they should not (your location, your messages)\n\nImportant: If you suspect an intimate partner has installed spyware, do NOT confront them before securing yourself. Contact a trusted person first." },
          { title: "How to Check for Spy Apps", slug: "check-spy-apps", type: "activity", durationMinutes: 20, order: 1,
            quizQuestions: [
              { question: "Where should you check for spy apps on Android?", options: ["Only the home screen", "Settings → Apps → Show all apps", "Only the Play Store", "The phone's camera"], correctIndex: 1, explanation: "Spy apps hide from the home screen — you must check the full app list in Settings." },
            ],
            content: "Step-by-step check:\n\nAndroid:\n1. Go to Settings → Apps → Show all apps\n2. Look for apps you do not recognise with generic names\n3. Check for apps with device admin privileges: Settings → Security → Device admin apps\n4. Look for accessibility services you did not enable\n5. Check data usage: Settings → Network → Data usage — look for unknown apps using data\n\niPhone:\n1. Check for unfamiliar profiles: Settings → General → VPN & Device Management\n2. Look for apps you did not install\n3. Check location sharing: Settings → Privacy → Location Services\n4. Check if your iCloud account is signed in on unknown devices\n\nPractical Task: Complete this check on your phone right now. Remove anything suspicious." },
          { title: "Locking Down Your Phone", slug: "lock-down-phone", type: "text", durationMinutes: 15, order: 2, quizQuestions: [],
            content: "Essential phone security:\n\n1. Use a strong screen lock — 6-digit PIN minimum, or biometric\n2. Do NOT share your phone PIN with anyone\n3. Disable 'Install from unknown sources' on Android\n4. Keep your operating system updated\n5. Review app permissions monthly: Settings → Privacy\n6. Disable lock screen notification previews (prevents others reading your messages)\n7. Enable 'Find My Phone' so you can remote-wipe if stolen\n\nPractical Task: Change your screen lock PIN today. Disable lock screen previews. Review your app permissions." },
          { title: "App Permissions Audit", slug: "app-permissions", type: "activity", durationMinutes: 15, order: 3, quizQuestions: [],
            content: "Your apps may have access to more than they need.\n\nReview these permissions:\n• Camera — does a calculator app need your camera? No.\n• Microphone — does a shopping app need your mic? No.\n• Location — does a game need your location? No.\n• Contacts — does a flashlight app need your contacts? No.\n\nGo to Settings → Privacy and review each permission category. Revoke anything unnecessary.\n\nPractical Task: Complete a full permission audit. Remove at least 3 unnecessary permissions today." },
          { title: "Passwords and 2FA", slug: "passwords-2fa", type: "text", durationMinutes: 15, order: 4,
            quizQuestions: [
              { question: "What is the safest form of two-factor authentication?", options: ["SMS codes", "Email codes", "App-based authenticator (Google Authenticator)", "Security questions"], correctIndex: 2, explanation: "App-based 2FA cannot be intercepted by SIM swap attacks, unlike SMS codes." },
            ],
            content: "Your password is your first line of defence.\n\nPassword rules:\n• Minimum 12 characters\n• Mix letters, numbers, symbols\n• Never reuse passwords across accounts\n• Never use your name, birthday, or phone number\n• Use a password manager if possible\n\nTwo-Factor Authentication (2FA):\n• Enable 2FA on every account that supports it\n• Prefer app-based 2FA (Google Authenticator, Authy) over SMS\n• SMS 2FA can be intercepted by SIM swap attacks\n• Store backup codes in a safe place\n\nPractical Task: Enable 2FA on your email, social media, and MoMo accounts today." },
          { title: "Phone Privacy Review Quiz", slug: "phone-quiz", type: "quiz", durationMinutes: 10, order: 5,
            quizQuestions: [
              { question: "What is the most common way spy apps are installed?", options: ["Through phone calls", "Physical access to your unlocked phone", "Through Bluetooth", "By sending a text message"], correctIndex: 1, explanation: "Most stalkerware requires physical access to install — protect your phone lock." },
              { question: "What should you do FIRST if you suspect your partner has installed spyware?", options: ["Confront them immediately", "Delete the app", "Contact a trusted person for safety", "Factory reset your phone"], correctIndex: 2, explanation: "Ensure your physical safety first before taking any action on the device." },
              { question: "Which password is strongest?", options: ["password123", "myname2024", "K9#mPx$2vLqR", "123456789"], correctIndex: 2, explanation: "A mix of random letters, numbers, and symbols is strongest." },
            ],
            content: "Complete this quiz to earn your certificate." },
        ],
      },
    ],
  },
  {
    title: "Sextortion, Blackmail and Online Harassment Response",
    slug: "sextortion-blackmail-response",
    excerpt: "A practical response protocol for sextortion, blackmail, and online harassment targeting women and girls.",
    description: "If someone is threatening to share your intimate images, demanding money, or harassing you online — this course gives you a step-by-step response protocol. Built by cybersecurity professionals, tested in real cases across Ghana and West Africa.",
    category: "online-safety", level: "intermediate", durationHours: 3, instructor: "DK Cyber",
    isFree: true, isPublished: true,
    tags: ["sextortion", "blackmail", "online-harassment", "response"],
    learningOutcomes: ["Respond to sextortion threats without panicking", "Preserve evidence for law enforcement", "Report to platforms, police, and support organisations", "Protect your accounts and digital identity after an incident"],
    modules: [{ title: "Responding to Sextortion", slug: "sextortion-response", description: "Step-by-step protocol when you receive a sextortion threat.", order: 0,
      lessons: [
        { title: "First 24 Hours: What To Do", slug: "first-24-hours", type: "text", durationMinutes: 25, order: 0, quizQuestions: [],
          content: "If someone is threatening to share your intimate images or demanding money, the first thing you must know is: do not pay. Paying does not make it stop.\n\nFirst 24 hours:\n1. Do NOT respond to the threat\n2. Screenshot everything — messages, profiles, demands\n3. Do NOT delete any messages\n4. Lock down your social media (set to private)\n5. Tell a trusted person in your safety circle\n6. Report to the platform where the threat was made\n7. Contact police / Cyber Crime Unit" },
      ],
    }],
  },
  {
    title: "Social Media Safety for Girls and Women",
    slug: "social-media-safety",
    excerpt: "Protect your identity, manage your digital footprint, and stay safe on social media platforms.",
    description: "Social media is where women connect, build careers, and express themselves — but it is also where stalkers, scammers, and harassers find their targets. This course covers privacy settings, identity protection, and safe online behaviour for every major platform.",
    category: "online-safety", level: "beginner", durationHours: 3, instructor: "SafeHer Foundation",
    isFree: true, isPublished: true,
    tags: ["social-media", "privacy", "digital-safety", "online"],
    learningOutcomes: ["Configure privacy settings on major social media platforms", "Protect your identity from social engineering", "Recognise and respond to online stalking", "Build a safe and professional online presence"],
    modules: [{ title: "Social Media Fundamentals", slug: "social-fundamentals", description: "Core principles for staying safe on any platform.", order: 0,
      lessons: [{ title: "Your Digital Footprint", slug: "digital-footprint", type: "text", durationMinutes: 15, order: 0, quizQuestions: [],
        content: "Every post, comment, photo, and check-in creates a digital footprint. This lesson shows you what information you are revealing, who can see it, and how to control your exposure." }],
    }],
  },
  {
    title: "Campus and Hostel Safety",
    slug: "campus-hostel-safety",
    excerpt: "Safety education designed for female students living on university campuses and in hostels across Africa.",
    description: "University should be the safest years of your life — but for too many women in Africa, campus brings new risks. This course covers accommodation safety, social situations, campus security resources, and emergency protocols.",
    category: "campus-safety", level: "beginner", durationHours: 4, instructor: "SafeHer Foundation",
    isFree: true, isPublished: true,
    tags: ["campus", "hostel", "university", "students"],
    learningOutcomes: ["Assess and improve hostel and accommodation security", "Navigate social situations safely", "Use campus security and welfare resources effectively", "Build a campus safety network with fellow students"],
    modules: [{ title: "Accommodation Security", slug: "accommodation", description: "Make your hostel or rental as safe as possible.", order: 0,
      lessons: [{ title: "Choosing Safe Accommodation", slug: "choosing-accommodation", type: "text", durationMinutes: 20, order: 0, quizQuestions: [],
        content: "Where you live determines much of your safety on campus. This lesson covers what to look for when choosing accommodation — from physical security features to neighbourhood safety and proximity to emergency services." }],
    }],
  },
];
